# Use the official PostgreSQL image from Docker Hub
FROM postgres:alpine
 
# Environment variables for PostgreSQL configuration
ENV POSTGRES_USER=hanan
ENV POSTGRES_PASSWORD=1234hanan
ENV POSTGRES_DB=shanan_db
ENV POSTGRES_HOST: hnalmutairi-db-service
ENV POSTGRES_PORT: '5432'
 
# Mount a volume for persistent data storage
VOLUME /var/lib/postgresql/data
 
# Expose the PostgreSQL port
EXPOSE 5432
